/**
 * Port parity: the TypeScript engine must reproduce the Python engine's state
 * transitions exactly (BUILD-SPEC §14, AC-001 and AC-003).
 *
 * Vectors are generated by `backend/scripts/export_vectors.py`. They carry
 * explicit states and explicit actions, so they are RNG-independent — the two
 * engines draw tiles differently by design (A-003) and are still held to the
 * same rules here.
 */

import { gunzipSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  Action,
  GAME_OVER,
  GameState,
  applyAction,
  eventToDict,
  settleRound,
  type GameEvent,
} from '../src/engine';

const VECTORS = new URL('./vectors/', import.meta.url);

function readJson<T>(name: string): T {
  const path = fileURLToPath(new URL(name, VECTORS));
  const raw = name.endsWith('.gz')
    ? gunzipSync(readFileSync(path)).toString('utf-8')
    : readFileSync(path, 'utf-8');
  return JSON.parse(raw) as T;
}

interface Step {
  action_id: number;
  expected_state: Record<string, unknown>;
  expected_events: Record<string, unknown>[];
}

interface Vector {
  name: string;
  note: string;
  initial_state: Record<string, unknown>;
  steps: Step[];
}

/**
 * Replay one vector the way the exporter recorded it: apply, then settle when
 * drafting is done — but never deal the next round, which would consume
 * randomness. Returns the first mismatch, or null.
 */
function replay(vector: Vector): string | null {
  const state = GameState.fromDict(vector.initial_state);

  for (let i = 0; i < vector.steps.length; i += 1) {
    const step = vector.steps[i];
    const action = Action.fromId(step.action_id);
    const undo = applyAction(state, action);
    const events: GameEvent[] = [undo.event];
    if (state.draftingDone()) events.push(...settleRound(state));

    const gotEvents = events.map(eventToDict);
    if (JSON.stringify(gotEvents) !== JSON.stringify(step.expected_events)) {
      try {
        expect(gotEvents).toEqual(step.expected_events);
      } catch (err) {
        return `${vector.name} step ${i} (${action.describe()}) events:\n${(err as Error).message}`;
      }
    }

    const gotState = state.toDict();
    try {
      expect(gotState).toEqual(step.expected_state);
    } catch (err) {
      return `${vector.name} step ${i} (${action.describe()}) state:\n${(err as Error).message}`;
    }

    if (state.phase === GAME_OVER) break;
  }
  return null;
}

describe('action encoding', () => {
  it('matches Action.action_id for all 180 combinations (AC-003)', () => {
    const { actions } = readJson<{
      actions: { source: number; color: number; dest: number; action_id: number }[];
    }>('action_ids.json');

    expect(actions).toHaveLength(180);
    for (const a of actions) {
      const action = new Action(a.source, a.color, a.dest);
      expect(action.actionId).toBe(a.action_id);
      const round = Action.fromId(a.action_id);
      expect([round.source, round.color, round.dest]).toEqual([a.source, a.color, a.dest]);
    }
  });
});

describe('edge-case vectors', () => {
  const { vectors } = readJson<{ vectors: Vector[] }>('edge_cases.json');

  it('exports every documented edge case', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(12);
  });

  for (const vector of vectors) {
    it(`${vector.name} — ${vector.note}`, () => {
      expect(replay(vector)).toBeNull();
    });
  }
});

describe('full-game vectors', () => {
  const { games } = readJson<{
    games: { seed: number; segments: Vector[] }[];
  }>('games.json.gz');

  it('exports at least 200 complete games (§14.2)', () => {
    expect(games.length).toBeGreaterThanOrEqual(200);
  });

  it('replays every round of every game with deep-equal state and events', () => {
    const failures: string[] = [];
    for (const game of games) {
      for (const segment of game.segments) {
        const failure = replay(segment);
        if (failure) failures.push(failure);
      }
    }
    expect(failures.slice(0, 3).join('\n\n')).toBe('');
  });
});
